name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22
          - 20
          - 18
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - if: ${{ matrix.node-version == 22 }}
        name: Check formatting
        run: pnpm prettier --check "**/*.{js,json,md,ts}"
      - if: ${{ matrix.node-version == 22 }}
        name: Check types
        run: pnpm tsc --noEmit
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
      - if: ${{ matrix.node-version == 22 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@d561fd8350291f6c88df0c3b081676c830861b06 # v1.0.11
