name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - if: ${{ matrix.node-version == 24 }}
        name: Check formatting
        run: pnpm lint
      - if: ${{ matrix.node-version == 24 }}
        name: Check types
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test
      - if: ${{ matrix.node-version == 24 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@bfa00f627638fb016d8b0eb331ee634ff44cd2da # v2.0.0
