name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
          - 22
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.node-version == 26 }}
        name: Check formatting
        run: npm run lint
      - if: ${{ matrix.node-version == 26 }}
        name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
      - if: ${{ matrix.node-version == 26 }}
        name: Check for packaging errors
        uses: kirkeaton/action-publint@d2adcfea2a5f505fde2b20746af44c698a12583b # v2.1.1
